### ISSUE TITLE
Are you amending your initial commit?

### ISSUE THREAD

**Issue by JudahDoupe** [0x2b3bfa0/blob-opera-toolkit#1]
A friend and I want to add additional functionality to your toolkit, but it we aren't able to merge in your latest changes because your initial commit keeps changing.  This causes a `fatal: refusing to merge unrelated histories` error when attempting to merge.  We'd like to make a pull request into your repo when we're done, but we need a proper git history to be able to do that.

**Comment by 0x2b3bfa0** [comment]
Sorry, @JudahDoupe, the project has suffered some insanely drastic changes and previous commits didn't have enough quality to be preserved. This tool evolved from a quick hack to... well, a _slow hack_ in two days.

Now everything is frozen and you can fork and perform pull requests as usual.

**Comment by 0x2b3bfa0** [comment]
Feel free to reopen this issue if required.
